# Generated by Django 4.1.2 on 2022-11-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="continent",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
