# Generated by Django 4.1.2 on 2022-11-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travels", "0002_alter_continent_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="iata",
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
